name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Emu Box
        uses: docker/setup-qemu-action@v1
      - name: Docker Buildx Box
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_U }}
          password: ${{ secrets.DOCKER_P }}
      - name: Doozer
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ryanabelanger/stake_mtrc_cnsmr:latest,ryanabelanger/stake_mtrc_cnsmr:0.6.3
